services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/opt/project/backend
    ports:
      - "8000:8000"
    command: "./startup.sh"
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass
    depends_on:
      - database

  database:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
