services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/opt/project/backend
    ports:
      - "8000:8000"
    command: sh -c "chmod +x startup.sh && ./startup.sh"
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/opt/project/frontend
      - /opt/project/frontend/node_modules
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    command: sh -c "npm start"

  database:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
