services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/code/backend
    ports:
      - "8000:8000"
    command: "./wait-for-it.sh database:5432 -- python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/code/frontend
      - /code/frontend/node_modules
    environment:
      - WATCHPACK_POLLING=true

    ports:
      - "3000:3000"
    command: "npm start"

  database:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
