services:
  backend:
    build:
      context:
        ./backend
    ports:
      - "8000:8000"
    command: sh -c "sleep 3 && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: sh -c "npm start"
    depends_on:
      - backend

  database:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
